In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [2]:
df= pd.read_csv('pv_data_2012_2017.csv')
print(df.head(10))

                    time_15m  tot_pv  tot_pv_castelfidardo  tot_pv_cit  \
0  2012-01-01 01:00:00+01:00     NaN                   NaN         NaN
1  2012-01-01 01:15:00+01:00     NaN                   NaN         NaN
2  2012-01-01 01:30:00+01:00     NaN                   NaN         NaN
3  2012-01-01 01:45:00+01:00     NaN                   NaN         NaN
4  2012-01-01 02:00:00+01:00     NaN                   NaN         NaN
5  2012-01-01 02:15:00+01:00     NaN                   NaN         NaN
6  2012-01-01 02:30:00+01:00     NaN                   NaN         NaN
7  2012-01-01 02:45:00+01:00     NaN                   NaN         NaN
8  2012-01-01 03:00:00+01:00     NaN                   NaN         NaN
9  2012-01-01 03:15:00+01:00     NaN                   NaN         NaN

   tot_pv_aule_p  tot_pv_aule_p_i1  tot_pv_aule_p_i2  tot_pv_aule_r  \
0            NaN               NaN               NaN            NaN
1            NaN               NaN               NaN            NaN
2            NaN               NaN               NaN            NaN
3            NaN               NaN               NaN            NaN
4            NaN               NaN               NaN            NaN
5            NaN               NaN               NaN            NaN
6            NaN               NaN               NaN            NaN
7            NaN               NaN               NaN            NaN
8            NaN               NaN               NaN            NaN
9            NaN               NaN               NaN            NaN

   tot_pv_ec  tot_pv_ec_inv1  tot_pv_ec_inv2  tot_pv_ec_inv3  tot_pv_ec_inv4  \
0        NaN             NaN             NaN             NaN             NaN
1        NaN             NaN             NaN             NaN             NaN
2        NaN             NaN             NaN             NaN             NaN
3        NaN             NaN             NaN             NaN             NaN
4        NaN             NaN             NaN             NaN             NaN
5        NaN             NaN             NaN             NaN             NaN
6        NaN             NaN             NaN             NaN             NaN
7        NaN             NaN             NaN             NaN             NaN
8        NaN             NaN             NaN             NaN             NaN
9        NaN             NaN             NaN             NaN             NaN

   tot_pv_i3p  tot_pv_i3p_est  tot_pv_i3p_ovest
0         NaN             NaN               NaN
1         NaN             NaN               NaN
2         NaN             NaN               NaN
3         NaN             NaN               NaN
4         NaN             NaN               NaN
5         NaN             NaN               NaN
6         NaN             NaN               NaN
7         NaN             NaN               NaN
8         NaN             NaN               NaN
9         NaN             NaN               NaN

In [3]:
df

,time_15m,tot_pv,tot_pv_castelfidardo,tot_pv_cit,tot_pv_aule_p,tot_pv_aule_p_i1,tot_pv_aule_p_i2,tot_pv_aule_r,tot_pv_ec,tot_pv_ec_inv1,tot_pv_ec_inv2,tot_pv_ec_inv3,tot_pv_ec_inv4,tot_pv_i3p,tot_pv_i3p_est,tot_pv_i3p_ovest
0,2012-01-01 01:00:00+01:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2012-01-01 01:15:00+01:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2012-01-01 01:30:00+01:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2012-01-01 01:45:00+01:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2012-01-01 02:00:00+01:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209493,2017-12-31 23:45:00+01:00,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
209494,2018-01-01 00:00:00+01:00,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
209495,2018-01-01 00:15:00+01:00,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
209496,2018-01-01 00:30:00+01:00,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
209497,2018-01-01 00:45:00+01:00,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0

In [4]:
df1= pd.read_csv('pv_data_2018_2020.csv')
df1

,time_15m,tot_pv,tot_pv_castelfidardo,tot_pv_cit,tot_pv_aule_p,tot_pv_aule_p_i1,tot_pv_aule_p_i2,tot_pv_aule_r,tot_pv_ec,tot_pv_ec_inv1,tot_pv_ec_inv2,tot_pv_ec_inv3,tot_pv_ec_inv4,tot_pv_i3p,tot_pv_i3p_est,tot_pv_i3p_ovest
0,2018-01-01 01:00:00+01:00,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
1,2018-01-01 01:15:00+01:00,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
2,2018-01-01 01:30:00+01:00,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
3,2018-01-01 01:45:00+01:00,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
4,2018-01-01 02:00:00+01:00,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105211,2020-12-31 23:45:00+01:00,0.0,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,0.0,0.0
105212,2021-01-01 00:00:00+01:00,0.0,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,0.0,0.0
105213,2021-01-01 00:15:00+01:00,0.0,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,0.0,0.0
105214,2021-01-01 00:30:00+01:00,0.0,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,0.0,0.0
105215,2021-01-01 00:45:00+01:00,0.0,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,0.0,0.0

In [6]:
df2= pd.read_csv('pv_data_2021_2024.csv')
df2

,time_15m,tot_pv,tot_pv_castelfidardo,tot_pv_cit,tot_pv_aule_p,tot_pv_aule_p_i1,tot_pv_aule_p_i2,tot_pv_aule_r,tot_pv_ec,tot_pv_ec_inv1,tot_pv_ec_inv2,tot_pv_ec_inv3,tot_pv_ec_inv4,tot_pv_i3p,tot_pv_i3p_est,tot_pv_i3p_ovest
0,2021-01-01 01:00:00+01:00,0.000,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,0.0,0.0
1,2021-01-01 01:15:00+01:00,0.000,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,0.0,0.0
2,2021-01-01 01:30:00+01:00,0.000,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,0.0,0.0
3,2021-01-01 01:45:00+01:00,0.000,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,0.0,0.0
4,2021-01-01 02:00:00+01:00,0.000,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140251,2024-12-31 23:45:00+01:00,0.000,0.000,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0
140252,2025-01-01 00:00:00+01:00,0.000,0.000,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0
140253,2025-01-01 00:15:00+01:00,0.000,0.000,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0
140254,2025-01-01 00:30:00+01:00,0.000,0.000,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0
140255,2025-01-01 00:45:00+01:00,0.048,0.048,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0

In [ ]:
# Concatenate all three dataframes
merged_df = pd.concat([df, df1, df2], ignore_index=True)
print(f"Merged dataframe shape: {merged_df.shape}")
print(merged_df.head())

merged_df.to_csv('merged_pv_data.csv', index=False)

Merged dataframe shape: (454970, 16)
                    time_15m  tot_pv  tot_pv_castelfidardo  tot_pv_cit  \
0  2012-01-01 01:00:00+01:00     NaN                   NaN         NaN
1  2012-01-01 01:15:00+01:00     NaN                   NaN         NaN
2  2012-01-01 01:30:00+01:00     NaN                   NaN         NaN
3  2012-01-01 01:45:00+01:00     NaN                   NaN         NaN
4  2012-01-01 02:00:00+01:00     NaN                   NaN         NaN

   tot_pv_aule_p  tot_pv_aule_p_i1  tot_pv_aule_p_i2  tot_pv_aule_r  \
0            NaN               NaN               NaN            NaN
1            NaN               NaN               NaN            NaN
2            NaN               NaN               NaN            NaN
3            NaN               NaN               NaN            NaN
4            NaN               NaN               NaN            NaN

   tot_pv_ec  tot_pv_ec_inv1  tot_pv_ec_inv2  tot_pv_ec_inv3  tot_pv_ec_inv4  \
0        NaN             NaN             NaN             NaN             NaN
1        NaN             NaN             NaN             NaN             NaN
2        NaN             NaN             NaN             NaN             NaN
3        NaN             NaN             NaN             NaN             NaN
4        NaN             NaN             NaN             NaN             NaN

   tot_pv_i3p  tot_pv_i3p_est  tot_pv_i3p_ovest
0         NaN             NaN               NaN
1         NaN             NaN               NaN
2         NaN             NaN               NaN
3         NaN             NaN               NaN
4         NaN             NaN               NaN

Merged dataframe shape: (454970, 16)
                    time_15m  tot_pv  tot_pv_castelfidardo  tot_pv_cit  \
0  2012-01-01 01:00:00+01:00     NaN                   NaN         NaN
1  2012-01-01 01:15:00+01:00     NaN                   NaN         NaN
2  2012-01-01 01:30:00+01:00     NaN                   NaN         NaN
3  2012-01-01 01:45:00+01:00     NaN                   NaN         NaN
4  2012-01-01 02:00:00+01:00     NaN                   NaN         NaN

   tot_pv_aule_p  tot_pv_aule_p_i1  tot_pv_aule_p_i2  tot_pv_aule_r  \
0            NaN               NaN               NaN            NaN
1            NaN               NaN               NaN            NaN
2            NaN               NaN               NaN            NaN
3            NaN               NaN               NaN            NaN
4            NaN               NaN               NaN            NaN

   tot_pv_ec  tot_pv_ec_inv1  tot_pv_ec_inv2  tot_pv_ec_inv3  tot_pv_ec_inv4  \
0        NaN             NaN             NaN             NaN             NaN
1        NaN             NaN             NaN             NaN             NaN
2        NaN             NaN             NaN             NaN             NaN
3        NaN             NaN             NaN             NaN             NaN
4        NaN             NaN             NaN             NaN             NaN

   tot_pv_i3p  tot_pv_i3p_est  tot_pv_i3p_ovest
0         NaN             NaN               NaN
1         NaN             NaN               NaN
2         NaN             NaN               NaN
3         NaN             NaN               NaN
4         NaN             NaN               NaN

,time_15m,tot_pv,tot_pv_castelfidardo,tot_pv_cit,tot_pv_aule_p,tot_pv_aule_p_i1,tot_pv_aule_p_i2,tot_pv_aule_r,tot_pv_ec,tot_pv_ec_inv1,tot_pv_ec_inv2,tot_pv_ec_inv3,tot_pv_ec_inv4,tot_pv_i3p,tot_pv_i3p_est,tot_pv_i3p_ovest
0,2012-01-01 01:00:00+01:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2012-01-01 01:15:00+01:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2012-01-01 01:30:00+01:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2012-01-01 01:45:00+01:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2012-01-01 02:00:00+01:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
454965,2024-12-31 23:45:00+01:00,0.000,0.000,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0
454966,2025-01-01 00:00:00+01:00,0.000,0.000,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0
454967,2025-01-01 00:15:00+01:00,0.000,0.000,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0
454968,2025-01-01 00:30:00+01:00,0.000,0.000,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0
454969,2025-01-01 00:45:00+01:00,0.048,0.048,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0